# Generated by Django 3.0.8 on 2020-08-05 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aspnetroleclaims',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('claimtype', models.TextField(blank=True, db_column='ClaimType', null=True)),
                ('claimvalue', models.TextField(blank=True, db_column='ClaimValue', null=True)),
            ],
            options={
                'db_table': 'AspNetRoleClaims',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Aspnetroles',
            fields=[
                ('id', models.CharField(db_column='Id', max_length=127, primary_key=True, serialize=False)),
                ('concurrencystamp', models.TextField(blank=True, db_column='ConcurrencyStamp', null=True)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=256, null=True)),
                ('normalizedname', models.CharField(blank=True, db_column='NormalizedName', max_length=256, null=True)),
            ],
            options={
                'db_table': 'AspNetRoles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Aspnetuserclaims',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('claimtype', models.TextField(blank=True, db_column='ClaimType', null=True)),
                ('claimvalue', models.TextField(blank=True, db_column='ClaimValue', null=True)),
            ],
            options={
                'db_table': 'AspNetUserClaims',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Aspnetuserlogins',
            fields=[
                ('loginprovider', models.CharField(db_column='LoginProvider', max_length=127, primary_key=True, serialize=False)),
                ('providerkey', models.CharField(db_column='ProviderKey', max_length=127)),
                ('providerdisplayname', models.TextField(blank=True, db_column='ProviderDisplayName', null=True)),
            ],
            options={
                'db_table': 'AspNetUserLogins',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Aspnetusers',
            fields=[
                ('id', models.CharField(db_column='Id', max_length=127, primary_key=True, serialize=False)),
                ('accessfailedcount', models.IntegerField(db_column='AccessFailedCount')),
                ('concurrencystamp', models.TextField(blank=True, db_column='ConcurrencyStamp', null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=256, null=True)),
                ('emailconfirmed', models.TextField(db_column='EmailConfirmed')),
                ('lockoutenabled', models.TextField(db_column='LockoutEnabled')),
                ('lockoutend', models.DateTimeField(blank=True, db_column='LockoutEnd', null=True)),
                ('normalizedemail', models.CharField(blank=True, db_column='NormalizedEmail', max_length=256, null=True)),
                ('normalizedusername', models.CharField(blank=True, db_column='NormalizedUserName', max_length=256, null=True)),
                ('passwordhash', models.TextField(blank=True, db_column='PasswordHash', null=True)),
                ('phonenumber', models.TextField(blank=True, db_column='PhoneNumber', null=True)),
                ('phonenumberconfirmed', models.TextField(db_column='PhoneNumberConfirmed')),
                ('securitystamp', models.TextField(blank=True, db_column='SecurityStamp', null=True)),
                ('twofactorenabled', models.TextField(db_column='TwoFactorEnabled')),
                ('username', models.CharField(blank=True, db_column='UserName', max_length=256, null=True)),
            ],
            options={
                'db_table': 'AspNetUsers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConCountries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('iso2', models.CharField(max_length=2)),
                ('ext_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'con_countries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConMunicipalities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('ext_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'con_municipalities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConStates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('ext_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'con_states',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Efmigrationshistory',
            fields=[
                ('migrationid', models.TextField(db_column='MigrationId', primary_key=True, serialize=False)),
                ('productversion', models.TextField(db_column='ProductVersion')),
            ],
            options={
                'db_table': '__EFMigrationsHistory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FarAnswers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value_raw', models.TextField(blank=True, null=True)),
                ('value_fixed', models.TextField()),
                ('validated', models.IntegerField()),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'far_answers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FarFarms',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('location_comments', models.CharField(blank=True, max_length=700, null=True)),
                ('enable', models.IntegerField()),
                ('ext_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'far_farms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FarPlots',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField()),
                ('enable', models.IntegerField()),
                ('ext_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'far_plots',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FarProductionEvents',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('enable', models.IntegerField()),
                ('ext_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField()),
                ('updated', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'far_production_events',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FarResponsesBool',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('raw_value', models.IntegerField(blank=True, null=True)),
                ('fixed_value', models.IntegerField(blank=True, null=True)),
                ('validated', models.IntegerField()),
            ],
            options={
                'db_table': 'far_responses_bool',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FarResponsesDate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('raw_value', models.DateTimeField(blank=True, null=True)),
                ('fixed_value', models.DateTimeField(blank=True, null=True)),
                ('validated', models.IntegerField()),
            ],
            options={
                'db_table': 'far_responses_date',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FarResponsesNumeric',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('raw_value', models.FloatField(blank=True, null=True)),
                ('fixed_value', models.FloatField(blank=True, null=True)),
                ('raw_units', models.CharField(blank=True, max_length=45, null=True)),
                ('fixed_units', models.CharField(blank=True, max_length=45, null=True)),
                ('validated', models.IntegerField()),
            ],
            options={
                'db_table': 'far_responses_numeric',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FarResponsesOptions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'far_responses_options',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FarResponsesText',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('raw_value', models.TextField(blank=True, null=True)),
                ('fixed_value', models.TextField(blank=True, null=True)),
                ('validated', models.IntegerField()),
            ],
            options={
                'db_table': 'far_responses_text',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FrmBlocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=500)),
                ('repeat', models.IntegerField()),
                ('times', models.IntegerField()),
                ('enable', models.IntegerField()),
                ('ext_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'frm_blocks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FrmForms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=500)),
                ('enable', models.IntegerField()),
                ('ext_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'frm_forms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FrmFormsSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=500)),
                ('value', models.TextField()),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'frm_forms_settings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FrmOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('label', models.CharField(max_length=400)),
                ('ext_id', models.CharField(blank=True, max_length=100, null=True)),
                ('enable', models.IntegerField()),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'frm_options',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FrmQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('label', models.CharField(max_length=400)),
                ('description', models.CharField(max_length=500)),
                ('type', models.CharField(max_length=8)),
                ('order', models.IntegerField()),
                ('enable', models.IntegerField()),
                ('ext_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'frm_questions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FrmQuestionsRules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=3)),
                ('type', models.CharField(max_length=13)),
                ('message', models.TextField(blank=True, null=True)),
                ('rule', models.TextField()),
            ],
            options={
                'db_table': 'frm_questions_rules',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SocAssociations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('enable', models.IntegerField()),
                ('ext_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'soc_associations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SocPeople',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kind_document', models.CharField(max_length=1)),
                ('sex', models.CharField(max_length=1)),
                ('document', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('cellphone', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=500, null=True)),
                ('ext_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'soc_people',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SocTechnicalAssistants',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('enable', models.IntegerField()),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'soc_technical_assistants',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Aspnetuserroles',
            fields=[
                ('userid', models.OneToOneField(db_column='UserId', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='paintmap.Aspnetusers')),
            ],
            options={
                'db_table': 'AspNetUserRoles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Aspnetusertokens',
            fields=[
                ('userid', models.OneToOneField(db_column='UserId', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='paintmap.Aspnetusers')),
                ('loginprovider', models.CharField(db_column='LoginProvider', max_length=127)),
                ('name', models.CharField(db_column='Name', max_length=127)),
                ('value', models.TextField(blank=True, db_column='Value', null=True)),
            ],
            options={
                'db_table': 'AspNetUserTokens',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FrmBlocksForms',
            fields=[
                ('form', models.OneToOneField(db_column='form', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='paintmap.FrmForms')),
                ('order', models.IntegerField()),
                ('enable', models.IntegerField()),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'frm_blocks_forms',
                'managed': False,
            },
        ),
    ]
